version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codebreaker-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-33polxadfmbe"
s3_prefix = "codebreaker-test"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "JudgeName=\"CodebreakerClone\""
