version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "codebreakercontest"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-s1r1qu4ekhbd"
s3_prefix = "codebreakercontest"
region = "ap-southeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "JudgeName=\"codebreakercontest\""
image_repositories = []
resolve_s3 = true
