AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  JudgeName:
    Description: "Insert name of Codebreaker Clone"
    Type: "String"
    Default: "codebreakercontest"

Globals:
  Function:
    Timeout: 60
    MemorySize: 1600
    Environment:
      Variables:
        judgeName: !Ref JudgeName
        accountId: !Ref AWS::AccountId
    Handler: lambda_function.lambda_handler
    Runtime: python3.9

Resources:
  ProblemValidationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: 
        Fn::Sub: ${JudgeName}-problem-validation
      CodeUri: lambda-functions/problem-validation
      Policies: 
        - AmazonDynamoDBFullAccess
        - AmazonS3ReadOnlyAccess
  RegradeProblemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${JudgeName}-regrade-problem
      Timeout: 900 # Extra time to iterate through all submissions
      CodeUri: lambda-functions/regrade-problem
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSStepFunctionsFullAccess
  WebsocketInvokeFunction:
    DependsOn: WebSocket
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${JudgeName}-websocket-invoke
      Timeout: 900 # Extra time to individually invoke each connection
      CodeUri: lambda-functions/websocket-invoke
      Policies:
        - AmazonAPIGatewayInvokeFullAccess
        - AmazonDynamoDBReadOnlyAccess
      Environment:
        Variables:
          WebSocketURI:
            Fn::Sub: https://${WebSocket}.execute-api.${AWS::Region}.amazonaws.com/Production
  WebsocketConnectionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${JudgeName}-websocket-connections
      CodeUri: lambda-functions/websocket-connections
      Policies:
        - AmazonDynamoDBFullAccess
  GraderProblemInitFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${JudgeName}-grader-problem-init
      CodeUri: lambda-functions/grader-problem-init
      Policies:
        - AmazonDynamoDBFullAccess      
  GraderProblemScorerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${JudgeName}-grader-problem-scorer
      CodeUri: lambda-functions/grader-problem-scorer
      Policies:
        - AmazonDynamoDBFullAccess
  TestcaseGraderWrapperFunction:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 128 # Wrapper function allocated minimal memory to minimise costs
      FunctionName:
        Fn::Sub: ${JudgeName}-testcase-grader-wrapper
      CodeUri: lambda-functions/testcase-grader-wrapper
      Policies:
        - AmazonDynamoDBFullAccess
        - AWSLambdaRole
  TestcaseGrader2048Function:
    Type: AWS::Serverless::Function
    Properties:
      MemorySize: 2600 # Larger memory to accomodate 2048MB Memory limit problems
      FunctionName:
        Fn::Sub: ${JudgeName}-testcase-grader-2048
      CodeUri: lambda-functions/testcase-grader
      Policies:
        - AmazonS3ReadOnlyAccess
  TestcaseGraderFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${JudgeName}-testcase-grader
      CodeUri: lambda-functions/testcase-grader
      Policies:
        - AmazonS3ReadOnlyAccess
  CompilerECRRepository: 
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: 
        Fn::Sub: ${JudgeName}-compiler-repository
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties: 
      RoleName:
        Fn::Sub: ${JudgeName}-codebuild
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
  CodeBuildProject: 
    Type: 'AWS::CodeBuild::Project'
    Properties:
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Name: 
        Fn::Sub:
          ${JudgeName}-codebuildproject
      Artifacts: 
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: 'aws/codebuild/standard:6.0'
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: AWS_DEFAULT_REGION
            Value: !Ref AWS::Region
          - Name: AWS_ACCOUNT_ID
            Value: !Ref AWS::AccountId
          - Name: IMAGE_REPO_NAME
            Value: 
              Fn::Sub: ${JudgeName}-compiler-repository
      Source:
        Type: GITHUB
        Location: 'https://github.com/singaporezoo/codebreaker-compiler'
        BuildSpec: buildspec.yml
  # CompilerFunction:
  #   Type: AWS::Lambda::Function
  #   Properties:
  #     FunctionName: 
  #       Fn::Sub: ${JudgeName}-problem-verification
  #     PackageType: Image
  #     ImageUri: 
  #       - 354145626860.dkr.ecr.ap-southeast-1.amazonaws.com/codebreakercontest-compiler-repository:latest
  #     Policies:
  #       - AmazonDynamoDBReadOnlyAccess
  #       - AmazonS3FullAccess
  GradingStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      Name:
        Fn::Sub:
          ${JudgeName}-grading
      DefinitionUri: state-machine/grading.asl.json
      DefinitionSubstitutions:
        ProblemInitFunctionArn: !GetAtt GraderProblemInitFunction.Arn
        TestcaseGraderWrapperFunctionArn: !GetAtt TestcaseGraderWrapperFunction.Arn
        ProblemScorerFunctionArn: !GetAtt GraderProblemScorerFunction.Arn
      Type: EXPRESS
      Policies:
        - AWSLambdaRole
  AttachmentsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${JudgeName}-attachments
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  TestdataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Sub: ${JudgeName}-testdata
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  SubmissionsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Sub: ${JudgeName}-submissions
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
      LifecycleConfiguration:
        Rules:
          - Id: clear-old-compiled
            Prefix: compiled/
            Status: Enabled
            ExpirationInDays: 1
  StatementsBucket:
    Type: AWS::S3::Bucket
    Description: Statements bucket is public to allow statements to be rendered on client-side
    Properties:
      BucketName:
        Fn::Sub: ${JudgeName}-statements
      AccessControl: PublicRead
      PublicAccessBlockConfiguration:
        BlockPublicAcls: False
        BlockPublicPolicy: False
        IgnorePublicAcls: False
        RestrictPublicBuckets: False
  GradersBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Sub: ${JudgeName}-graders
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  CheckersBucket: 
    Type: AWS::S3::Bucket
    Properties:
      BucketName: 
        Fn::Sub: ${JudgeName}-checkers
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: True
        BlockPublicPolicy: True
        IgnorePublicAcls: True
        RestrictPublicBuckets: True
  AnnouncementsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-announcements
      AttributeDefinitions:
        - AttributeName: announceId
          AttributeType: S
      KeySchema:
        - AttributeName: announceId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ClarificationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-clarifications
      AttributeDefinitions:
        - AttributeName: clarificationId
          AttributeType: N
        - AttributeName: askedBy
          AttributeType: S
      KeySchema:
        - AttributeName: clarificationId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: askedByIndex
          KeySchema:
            - AttributeName: askedBy
              KeyType: HASH
          Projection:
            ProjectionType: ALL
  ContestsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-contests
      AttributeDefinitions:
        - AttributeName: contestId
          AttributeType: S
      KeySchema:
        - AttributeName: contestId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  GlobalCountersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-global-counters
      AttributeDefinitions:
        - AttributeName: counterId
          AttributeType: S
      KeySchema:
        - AttributeName: counterId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  ProblemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-problems
      AttributeDefinitions:
        - AttributeName: problemName
          AttributeType: S
      KeySchema:
        - AttributeName: problemName
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  SubmissionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-submissions
      AttributeDefinitions:
        - AttributeName: subId
          AttributeType: N
        - AttributeName: problemName
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: subId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: problemIndex
          KeySchema:
            - AttributeName: problemName
              KeyType: HASH
            - AttributeName: subId
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes:
              - submissionTime
              - maxTime
              - maxMemory
              - score
              - username
              - subtaskScores
              - totalScores
              - language
              - compileErrorMessage
        - IndexName: usernameIndex
          KeySchema: 
            - AttributeName: username
              KeyType: HASH
            - AttributeName: subId
              KeyType: RANGE
          Projection:
            ProjectionType: INCLUDE
            NonKeyAttributes: 
              - submissionTime
              - maxTime
              - maxMemory
              - problemName              
              - totalScore
              - language
              - compileErrorMessage
  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-users
      AttributeDefinitions:
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: username
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
  WebSocketTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${JudgeName}-websocket
      AttributeDefinitions:
        - AttributeName: connectionId
          AttributeType: S
        - AttributeName: accountRole
          AttributeType: S
        - AttributeName: username
          AttributeType: S
      KeySchema:
        - AttributeName: connectionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: accountRoleIndex
          KeySchema:
            - AttributeName: accountRole
              KeyType: HASH
            - AttributeName: connectionId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: usernameIndex
          KeySchema:
            - AttributeName: username
              KeyType: HASH
            - AttributeName: connectionId
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: expiryTime
        Enabled: True
  WebSocket:
    Type: AWS::ApiGatewayV2::Api
    Properties:
      Name:
        Fn::Sub: ${JudgeName}-websocket
      ProtocolType: WEBSOCKET
      RouteSelectionExpression: "$request.body.action"
  ConnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $connect
      RouteResponseSelectionExpression: '$default'
      AuthorizationType: NONE
      ApiKeyRequired: false
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WeSocketIntegration
  DisconnectRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $disconnect
      RouteResponseSelectionExpression: '$default'
      AuthorizationType: NONE
      ApiKeyRequired: false
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WeSocketIntegration
  MessageRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: message
      RouteResponseSelectionExpression: '$default'
      AuthorizationType: NONE
      ApiKeyRequired: false
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WeSocketIntegration
  DefaultRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref WebSocket
      RouteKey: $default
      RouteResponseSelectionExpression: '$default'
      AuthorizationType: NONE
      ApiKeyRequired: false
      OperationName: ConnectRoute
      Target: !Join
        - '/'
        - - 'integrations'
          - !Ref WeSocketIntegration
  WeSocketIntegration:
    Type: AWS::ApiGatewayV2::Integration
    Properties:
      ApiId: !Ref WebSocket
      Description: Connect Integration
      IntegrationType: AWS_PROXY
      IntegrationUri: 
        Fn::Sub:
          arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${WebsocketConnectionsFunction.Arn}/invocations
  WebSocketDeployment:
    Type: AWS::ApiGatewayV2::Deployment
    DependsOn:
    - ConnectRoute
    - MessageRoute
    - DisconnectRoute
    - DefaultRoute
    Properties:
      ApiId: !Ref WebSocket
  WebSocketStage:
    Type: AWS::ApiGatewayV2::Stage
    Properties:
      StageName: Production
      Description: Production stage
      DeploymentId: !Ref WebSocketDeployment
      ApiId: !Ref WebSocket
  WebServerIamRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${JudgeName}-ec2main
      AssumeRolePolicyDocument: # Specifies that role is for EC2 instances only
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/IAMFullAccess # For creating IAM roles for each problem
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess 
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
        - arn:aws:iam::aws:policy/AWSStepFunctionsFullAccess # For grading of problems
  WebServerIamProfile:
    Type: AWS::IAM::InstanceProfile
    DependsOn: WebServerIamRole
    Properties:
      InstanceProfileName: 
        Fn::Sub: ${JudgeName}-ec2profile
      Roles:
        - Ref: WebServerIamRole
  WebServerSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupName: 
        Fn::Sub:
          ${JudgeName}-ec2SG 
      GroupDescription: Allows SSH and HTTP
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 22
          IpProtocol: 'tcp'
          ToPort: 22
        - CidrIp: 0.0.0.0/0
          FromPort: 80
          IpProtocol: 'tcp'
          ToPort: 80
        - CidrIp: 0.0.0.0/0
          FromPort: 8000
          IpProtocol: 'tcp'
          ToPort: 8000
  WebServer:
    Type: AWS::EC2::Instance
    DependsOn: 
      - WebServerIamProfile
      - GlobalCountersTable
    # Depends on global counters because the bootstrap script initialises global counter values
    # TODO: Add dependncy on cognito and users table, then create initial admin user from bootstrap
    Properties:
      InstanceType: t2.nano
      ImageId: ami-0b7e55206a0a22afc # Ubuntu 22.04 x64
      IamInstanceProfile: 
        Ref: WebServerIamProfile
      Tags: 
        - Key: Name
          Value: 
            Fn::Sub: ${JudgeName}-webserver
      SecurityGroupIds:
        - !Ref WebServerSecurityGroup
      UserData:
        Fn::Base64: 
          !Sub | 
            #!/bin/bash
            apt update
            apt install python3-pip -y
            apt install python3-venv -y
            apt install awscli -y
            apt install nginx -y
            cd home/ubuntu
            git clone https://github.com/dvdg6566/codebreaker-contest-manager
            cd codebreaker-contest-manager

            python3 -m venv virtualenv
            source virtualenv/bin/activate
            pip3 install -r requirements.txt

            touch password.py
            echo 'FLASK_SECRET_KEY = "PLACEHOLDER"' >> password.py

            mkdir config
            mkdir ~/.aws/

            {
              echo '[default]'
              echo 'region = ap-southeast-1'
              echo 'output = json'
            } >> config/awsconfig
            cp config/awsconfig ~/.aws/config

            {
              echo '[Unit]'
              echo 'Description=Gunicorn instance for a codebreaker'
              echo 'After=network.target'
              echo '[Service]'
              echo 'User=ubuntu'
              echo 'Group=www-data'
              echo 'WorkingDirectory=/home/ubuntu/codebreaker-contest-manager'
              echo 'ExecStart=/home/ubuntu/codebreaker-contest-manager/virtualenv/bin/gunicorn -b localhost:8000 app:app'
              echo 'Restart=always'
              echo '[Install]'
              echo 'WantedBy=multi-user.target'
            } >> config/systemd
            cp config/systemd /etc/systemd/system/codebreaker.service

            systemctl start codebreaker
            systemctl enable codebreaker
            systemctl start nginx
            systemctl enable nginx

            {
              echo 'server {'
              echo '    listen 80 default_server;'
              echo '    listen [::]:80 default_server;'
              echo '    server_name codebreaker;'
              echo '    location / {'
              echo '        proxy_pass http://127.0.0.1:8000;'
              echo '        include proxy_params;'
              echo '    }'
              echo '}'
            } >> config/nginx

            cp config/nginx /etc/nginx/sites-available/default 
            systemctl restart nginx
  WebServerEIP:
    Type: AWS::EC2::EIP
    DependsOn: WebServer
    Properties:
      InstanceId: !Ref WebServer
Outputs: 
  GatewayEndpoint: 
    Value: 
      Fn::Sub: https://${WebSocket}.execute-api.${AWS::Region}.amazonaws.com/production
  ECRURI:
    Value:
      Fn::Join:
        - ':'
        - - !GetAtt CompilerECRRepository.RepositoryUri
          - 'latest'
  WebServerIP:
    Description: Main web server IP address
    Value: !Ref WebServerEIP